name: referease
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  firebase_analytics: ^0.3.3
  firebase_auth: ^0.5.20
  google_sign_in:

  intl: ^0.15.7
  sqflite: any
  path_provider: ^0.4.0
  cloud_firestore: ^0.7.3
  firebase_storage:
  image_picker: ^0.4.10
  font_awesome_flutter: ^8.0.1
  fluttertoast: ^2.1.5
  share: ^0.5.3
  shared_preferences: ^0.4.2
  chopper: ^2.4.2
  provider: ^3.0.0+1
  connectivity: ^0.4.3+2
  built_value: ^6.7.0
  email_validator: '^1.0.0'
  progress_dialog: ^1.1.0+1
  progress_hud: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # flutter_launcher_icons: ^0.6.1
  chopper_generator: ^2.4.2
  built_value_generator: ^6.7.0
  # No version number means the latest version
  build_runner:
# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/refereasylogo.png"
  image_path_android: "assets/images/refereasylogo.png"
  image_path_ios: "assets/images/refereasylogo.png"
  adaptive_icon_background: "#FFFFFFFF"
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/background.jpg
    - assets/images/background_hoz.jpg
    - assets/images/reading.png
    - assets/images/pilebook.png
    - assets/images/book.png
    - assets/images/edit.png
    - assets/images/facebook.png
    - assets/images/google.png
    - assets/images/circle.png
    - assets/images/triangle.png
    - assets/images/doodlebg.jpg
    - assets/images/refereasylogo.png
    - assets/referease.db
    - assets/images/help/edit_source.png
    - assets/images/help/landing.png
    - assets/images/help/landing_2.png
    - assets/images/help/landing_3.png
    - assets/images/help/new_source.png
    - assets/images/help/new_summary.png
    - assets/images/help/pick_source.png
    - assets/images/help/summary.png
    - assets/images/help/summary_type.png

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
